
- name: app setup
  ansible.builtin.import_role:
    name: commom
    tasks_from: app-setup

- name: go
  ansible.builtin.import_role:
    name: commom
    tasks_from: go

- name: system restart
  ansible.builtin.import_role:
    name: commom
    tasks_from: systemd
